[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /home/wujiashu0421/Roarm_ROS/build/arm_controller/.pytest_cache
rootdir: /home/wujiashu0421/Roarm_ROS/src/arm_controller
plugins: ament-xmllint-0.12.9, launch-testing-1.0.4, ament-pep257-0.12.9, ament-lint-0.12.9, ament-copyright-0.12.9, launch-testing-ros-0.19.6, ament-flake8-0.12.9, colcon-core-0.15.1, cov-3.0.0
[1mcollecting ... [0m[1m
collected 3 items                                                              [0m

test/test_copyright.py [33ms[0m[32m                                                 [ 33%][0m
test/test_flake8.py [31mF[0m[31m                                                    [ 66%][0m
test/test_pep257.py [32m.[0m[31m                                                    [100%][0m

=================================== FAILURES ===================================
[31m[1m_________________________________ test_flake8 __________________________________[0m
[1m[31mtest/test_flake8.py[0m:23: in test_flake8
    [94massert[39;49;00m rc == [94m0[39;49;00m, \
[1m[31mE   AssertionError: Found 16 code style errors / warnings:[0m
[1m[31mE     ./arm_controller/controller_node.py:6:1: E302 expected 2 blank lines, found 1[0m
[1m[31mE     ./arm_controller/controller_node.py:7:1: W293 blank line contains whitespace[0m
[1m[31mE     ./arm_controller/controller_node.py:12:1: W293 blank line contains whitespace[0m
[1m[31mE     ./arm_controller/controller_node.py:18:5: E266 too many leading '#' for block comment[0m
[1m[31mE     ./arm_controller/controller_node.py:24:5: E266 too many leading '#' for block comment[0m
[1m[31mE     ./arm_controller/controller_node.py:27:1: E305 expected 2 blank lines after class or function definition, found 1[0m
[1m[31mE     ./arm_controller/controller_node.py:29:1: W391 blank line at end of file[0m
[1m[31mE     ./arm_controller/arm_node.py:5:1: F401 'geometry_msgs.msg.Twist' imported but unused[0m
[1m[31mE     ./arm_controller/arm_node.py:5:1: F401 'geometry_msgs.msg.Point' imported but unused[0m
[1m[31mE     ./arm_controller/arm_node.py:8:1: E302 expected 2 blank lines, found 1[0m
[1m[31mE     ./arm_controller/arm_node.py:15:1: W293 blank line contains whitespace[0m
[1m[31mE     ./arm_controller/arm_node.py:17:1: W293 blank line contains whitespace[0m
[1m[31mE     ./arm_controller/arm_node.py:18:9: F841 local variable 'msg' is assigned to but never used[0m
[1m[31mE     ./arm_controller/arm_node.py:22:1: E303 too many blank lines (3)[0m
[1m[31mE     ./arm_controller/arm_node.py:27:1: E305 expected 2 blank lines after class or function definition, found 1[0m
[1m[31mE     ./arm_controller/arm_node.py:28:11: W292 no newline at end of file[0m
[1m[31mE   assert 1 == 0[0m
----------------------------- Captured stdout call -----------------------------

./arm_controller/controller_node.py:6:1: E302 expected 2 blank lines, found 1
class CommNode(Node):
^

./arm_controller/controller_node.py:7:1: W293 blank line contains whitespace
    
^

./arm_controller/controller_node.py:12:1: W293 blank line contains whitespace
    
^

./arm_controller/controller_node.py:18:5: E266 too many leading '#' for block comment
    ## Initiate ROS 2 communication , equivlent to ROS::start in ros1 i think
    ^

./arm_controller/controller_node.py:24:5: E266 too many leading '#' for block comment
    ## Stop ROS communication service entirely
    ^

./arm_controller/controller_node.py:27:1: E305 expected 2 blank lines after class or function definition, found 1
if __name__ == '__main__':
^

./arm_controller/controller_node.py:29:1: W391 blank line at end of file

^

./arm_controller/arm_node.py:5:1: F401 'geometry_msgs.msg.Twist' imported but unused
from geometry_msgs.msg import Twist, Point, Pose
^

./arm_controller/arm_node.py:5:1: F401 'geometry_msgs.msg.Point' imported but unused
from geometry_msgs.msg import Twist, Point, Pose
^

./arm_controller/arm_node.py:8:1: E302 expected 2 blank lines, found 1
class ArmInfoNode(Node):
^

./arm_controller/arm_node.py:15:1: W293 blank line contains whitespace
    
^

./arm_controller/arm_node.py:17:1: W293 blank line contains whitespace
        
^

./arm_controller/arm_node.py:18:9: F841 local variable 'msg' is assigned to but never used
        msg = Pose()
        ^

./arm_controller/arm_node.py:22:1: E303 too many blank lines (3)
def main(args=None):
^

./arm_controller/arm_node.py:27:1: E305 expected 2 blank lines after class or function definition, found 1
if __name__ == "__main__":
^

./arm_controller/arm_node.py:28:11: W292 no newline at end of file
    main()          ^

2     E266 too many leading '#' for block comment
2     E302 expected 2 blank lines, found 1
1     E303 too many blank lines (3)
2     E305 expected 2 blank lines after class or function definition, found 1
2     F401 'geometry_msgs.msg.Twist' imported but unused
1     F841 local variable 'msg' is assigned to but never used
1     W292 no newline at end of file
4     W293 blank line contains whitespace
1     W391 blank line at end of file

7 files checked
16 errors

'E'-type errors: 7
'F'-type errors: 3
'W'-type errors: 6

Checked files:

* ./setup.py
* ./arm_controller/controller_node.py
* ./arm_controller/__init__.py
* ./arm_controller/arm_node.py
* ./test/test_flake8.py
* ./test/test_pep257.py
* ./test/test_copyright.py
----------------------------- Captured stderr call -----------------------------
option --max-complexity: please update from optparse string `type=` to argparse callable `type=` -- this will be an error in the future
[33m=============================== warnings summary ===============================[0m
test/test_flake8.py::test_flake8
test/test_flake8.py::test_flake8
  Warning: SelectableGroups dict interface is deprecated. Use select.

-- Docs: https://docs.pytest.org/en/stable/warnings.html
- generated xml file: /home/wujiashu0421/Roarm_ROS/build/arm_controller/pytest.xml -
=========================== short test summary info ============================
FAILED test/test_flake8.py::test_flake8 - AssertionError: Found 16 code style...
[31m============== [31m[1m1 failed[0m, [32m1 passed[0m, [33m1 skipped[0m, [33m2 warnings[0m[31m in 0.30s[0m[31m ==============[0m
